### ISSUE TITLE
Flask package issue

### ISSUE THREAD

**Issue by aniketgore** [cantrell/stable-diffusion-api-server#1]
I didn't see any discussion forum so posting it here if it might be helpful for others.
When I ran the server got no module as flask found so I had to install it using conda install flask, and then run the server.py using python server.py (not the python3 mentioned in the git).

**Comment by cantrell** [comment]
Interestingly, I get the opposite errors. When I run with python, I get the Flask error, but running with python3 fixes it. I think it has to do with associating the right version of python with the version used to install the dependencies. I'll add a note to the README. Thanks!
