### ISSUE TITLE
Allow using Automatic1111 setup as server

### ISSUE THREAD

**Issue by Ainaemaet** [cantrell/stable-diffusion-api-server#21]
Hello, after having some time to play around with the plugin I have to say it's quite a handy tool and I'm thoroughly enjoying it. 

So many of us however, use Automatic1111 webui for running local SD, and having to setup both is a little frustrating. 
If I could just run --api tag in Automatic and connect with your plugin that way (similarly to blender SD plugin 'AI Render'), it would eliminate the need to have to setup another env as well as worry about converting .cktp's, and would also allow us to utilize other already-existing addons like xformers.

**Comment by cantrell** [comment]
That's coming!

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4682
