### ISSUE TITLE
unable to connect to huggingface to download the model

### ISSUE THREAD

**Issue by yomope** [cantrell/stable-diffusion-api-server#3]
when i run server.py . i'v got :
**requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/CompVis/stable-diffusion-v1-4/resolve/main/model_index.json**

i'm correctly logged in with hugginface_cli and i my account has acces to the model on the site

**Comment by cantrell** [comment]
I left a step out of the instructions. You also need to agree to share your email address with Hugging Face in order to download the model. Please see the new Hugging Face instructions in the README. (Sorry about that.)
