### ISSUE TITLE
CUDA Out of memory errors

### ISSUE THREAD

**Issue by Ainaemaet** [cantrell/stable-diffusion-api-server#8]
Hello, really looking forwards to trying this plugin but I'm getting cuda oom error using local inference. 
I have a multi GPU setup that I use, running photoshop using my GTX 1080 and using a 2080Ti for stable diffusion. 
Using various webui's I have no issue with memory, even without using any low mem methods (2080Ti has 11gb so more than enough for SD) but I just can't manage to get it to work with photoshop running - at least not with your plugin (I can run Photoshop and generate Stable Diffusion images at the same time no issue, just not using this plugin to do so). 

Thank you for all the hard work you're putting in to all this. Would you please be able to help me figure out how to get this plugin working on my setup? Thank you!

**Comment by cantrell** [comment]
Hi, there. Are you able to generate images at the smallest resolution?

**Comment by Ainaemaet** [comment]
> Hi, there. Are you able to generate images at the smallest resolution?

Ok, I can indeed so that's good. I hadn't realized I had it set to my document resolution. Everything is working as expected, thank you. 


Do you have plans for implementing masking, inpainting, etc? I know there is another plugin (alpaca.io) that purports to do so but still waiting on an closed beta invite, it would be amazing if your plugin could have such feature!

**Comment by cantrell** [comment]
Yes, I will get those in as soon as I can get the quality to the point where I'm happy.
